# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name gcusum
#' @title Grouped-CUSUM chart
#' @description Calculate GCUSUM chart for non-risk-adjusted processes.
#' 
#' @param input_outcomes NumericMatrix, patient outcomes and block_id (continuous).
#' @param failure_prob double, accepted failure probability of null hypothesis.
#' @param delta double, odds multiplier.
#' @param control_limit double, control limit.
#' @param max_num_shuffles integer, number of shuffles.
#' @param seed integer.
#' @param quantiles NumericVector, quantiles that are returned.
#' @return gcusum NumericMatix, signal probability, average CUSUM value and specified quantiles for every observation.
#' @export
gcusum <- function(input_outcomes, failure_prob, delta, control_limit, max_num_shuffles, seed, quantiles) {
    .Call(`_cusum_gcusum`, input_outcomes, failure_prob, delta, control_limit, max_num_shuffles, seed, quantiles)
}

#' @name ragcusum
#' @title RA-Grouped-CUSUM chart
#' 
#' @description Calculate GCUSUM chart for risk-adjusted processes.
#' 
#' @param input_ra_outcomes NumericMatrix, patient outcomes and block_id (continuous).
#' @param control_limit double, control limit.
#' @param max_num_shuffles integer, number of shuffles.
#' @param seed integer.
#' @param quantiles NumericVector, quantiles that are returned.
#' @return ragcusum NumericMatix, signal probability, average CUSUM value and specified quantiles for every observation.
#'  
#' @export
ragcusum <- function(input_ra_outcomes, control_limit, max_num_shuffles, seed, quantiles) {
    .Call(`_cusum_ragcusum`, input_ra_outcomes, control_limit, max_num_shuffles, seed, quantiles)
}

